apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ randAlphaNum 32 | b64enc | quote }}
  wordpress-password: {{ randAlphaNum 32 | b64enc | quote }}
