apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storageSize }}
  {{- if .Values.mysql.storageClass }}
  storageClassName: {{ .Values.mysql.storageClass }}
  {{- end }}
