apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress.storageSize }}
  {{- if .Values.wordpress.storageClass }}
  storageClassName: {{ .Values.wordpress.storageClass }}
  {{- end }}
